### ISSUE TITLE
Presence Sensor

### ISSUE THREAD

**Issue by iamkriss973** [rbiremon/hass-comapsmarthome#3]
Thanks you for this plugin which works perfectly.
I would like to use the presence sensor in the thermostat. Do you think it is possible ?

 With Jeedom
![dashboard2](https://user-images.githubusercontent.com/84200003/235633322-6241258d-b702-4824-b55a-57ff7b4c864e.jpg)

Thanks

**Comment by rbiremon** [comment]
This was implemented in https://github.com/rbiremon/hass-comapsmarthome/releases/tag/v1.1.0

Note that presence detection is not very reliable because this integration is polling. 
I added a Binary Sensor that is "on" if presence has been detected in the last two minutes. The last presence date is available as an attribute.
